---
title: Receiving TDs Model
format: 
    html:
      embed-resources: true
author: Josh Allen
date: last-modified
execute: 
  warning: false
  message: false

---

## Introduction

As I have finished up my PhD and still on the industry job market I have found myself doing a lot of projects to satisfy some curiosity and introduce myself professionally outside of my work in political science. I love watching football and learning about football with most of my working time spent listening to various NFL podcasts and the *Learning Bayesian Stats* podcast. For the last few years I have had an inherent fascination with Bayesian stats. One of the great things about Bayesian stats is that we can talk about uncertainty in a more intuitive way and because of the mechanics of using Bayesian models we can get some awesome looking plots. 

I got interested in [Alex Andora and Maximilian Göbel's Soccer Factor Model](https://arxiv.org/abs/2412.05911).^[I am American so I will just call it Soccer and call American Football Football.] They extend a common model in asset pricing called the factor model where we adjust for macroeconomic factors to elicit whether a particular portfolio manager is skilled at picking stocks or if this could be explained by the economy improving or worsening. They extend this idea to soccer where we are adjusting for macro-factors that affect the team. Whatever remains is attributable to a player's individual skill. They focus on goal scoring as an observable feature of a player's latent skill. 

After reading through the example notebooks and the paper I thought that this was not only an interesting idea, but probably would have a pretty strong cross-over with touchdowns in football. If we take a quick peak at the data they look kind of like each other. The data that are used in the goals plot are a subset of the data that they use in their Sloan analytics paper. From my very limited knowledge of ball most of these guys seem pretty good so we are likely to see more players with one goal.
```{r}
#| label: r-setup
#| code-fold: true
library(AllenMisc)
library(patchwork)
library(arrow)
library(ggdist)
library(nflreadr)
library(tidyverse)

knitr::opts_chunk$set(python.reticulate = FALSE)

theme_set(theme_allen_minimal())

goals_data = read_csv('https://raw.githubusercontent.com/AlexAndorra/football-modeling/refs/heads/main/01_SFM/10_data/101_SFM/SFM_data_byPlayer.csv')

player_info = load_rosters(seasons = 2014:2024)

tds_games_data = load_pbp(
     season = 2014:2024)


joined_tds_games = tds_games_data |>
    left_join(player_info, join_by( season, receiver_player_id == gsis_id)) |>
        filter(complete_pass == 1, position %in% c('RB', 'WR', 'TE')) |>
    summarise(
        pass_tds_game = sum(pass_touchdown, na.rm = TRUE),
        .by = c(season, game_id, receiver_player_id)
    )


tds_plot = ggplot(
    joined_tds_games,
    aes(x = pass_tds_game, y = after_stat(count/sum(count)))
) +
    geom_histogram() +
    scale_y_continuous(labels = scales::comma) +
    labs(x = 'Receiving Touchdowns', caption = 'Data Provided by nflreadr', y = 'Proportion')

goals_plot = ggplot(
    goals_data,
    aes(x = goals_in_match, y = after_stat(count/sum(count)))
) +
    geom_histogram() +
    scale_y_continuous(labels = scales::comma) +
    labs(x = 'Goals', y = 'Proporition')

tds_plot + goals_plot

```


## Touchdowns and Factors 


Why touchdowns? Outside of being a fun excercise to see how a model designed for soccer translates to football I think there is at least a resonable football story for why we can use touchdowns as an outcome. There are lots of ways to be a productive pass catcher in the NFL. One way we can tap their latent ability is by the number of 


We can measure wide receiver production in a lot of different ways some of the most obvious alternative measurements are efficiency metrics like yards per route run, usage statistics like target share, or just modeling production whether this is receiving yards or yards after catch. In fairness to the `nflreadr` team they do have this data. You could totally model this data using offensive personnel as one of the groups then model your yards metric of choice. However, in my wildest dreams I would like to use this model throughout the season to inform fantasy football decisions. The participation data that is provided is fantastic, but you have to wait till the end of the season. 


```{python}
#| label: py-setup
#| code-fold: true

import polars as pl
import pandas as pd
import pymc as pm
import preliz as pz
import numpy as np
from scipy.special import logit
import matplotlib.pyplot as plt
import arviz as az
import nflreadpy as nfl
import xarray as xr
import os
import subprocess

os.environ["JAX_PLATFORMS"] = "cpu"
os.environ["XLA_FLAGS"] = "--xla_force_host_platform_device_count=8"

# seed = subprocess.run('curl "https://www.random.org/integers/?num=1&min=10000000&max=99999999&col=1&base=10&# format=plain&rnd=new"',
#     shell=True,
#     capture_output=True,
#     text=True)
rng = 87472715

full_pass_data = pl.scan_parquet("./processed_data/processed_passers_*.parquet").collect()

full_scores = nfl.load_schedules()

player_exp = nfl.load_players().select(
    pl.col("gsis_id", "display_name", "birth_date", "rookie_season")
)

```


